# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults: 
  run:
    working-directory: ./client

jobs:
  build:
      
    runs-on: ubuntu-latest  

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: BUILD CLIENT
      run: pwd
    - run: ls -la
    - run: npm -g install yarn    
    - run: yarn install
    - run: yarn build --if-present

    - name: Create zip
      uses: ihiroky/archive-action@v1
      with:
        root_dir: ./build
        file_path: maneja_client.zip